### ISSUE TITLE
Problem importing solution

### ISSUE THREAD

**Issue by jdungen** [thomassandsor/CustomerService#1]
Hi, 

When importing i get this error:

Kan de oplossing Customer Service - CS niet importeren: Convert Rules import: FAILURE: Template With Id = 558b4792-04c9-ea11-a812-000d3a2c81cd Does Not Exist

(Above part is in dutch), it says can not import solution customer serice CS

Maybe languace problem?

Thanks,
Jan

**Comment by jdungen** [comment]
Tried it on another instance with english lang. and it imported fine.

**Comment by thomassandsor** [comment]
Absolutely! Just saw the same error myself. I have a template that only works with English language pack. That template is included in the email to case. If you activate the 1033 English language it works :)

Please let me know it this works. I will also try to make it more global, but I just dont have unlimited time on my hands ;)

Thomas Sandsør

________________________________
From: jdungen ***@***.***>
Sent: Thursday, April 29, 2021 7:45:54 PM
To: thomassandsor/CustomerService ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thomassandsor/CustomerService] Problem importing solution (#1)


Hi,

When importing i get this error:

Kan de oplossing Customer Service - CS niet importeren: Convert Rules import: FAILURE: Template With Id = 558b4792-04c9-ea11-a812-000d3a2c81cd Does Not Exist

(Above part is in dutch), it says can not import solution customer serice CS

Maybe languace problem?

Thanks,
Jan
